### PR TITLE
Add LastPass Bank-paid account instructions

### PR DESCRIPTION
**Pull request by bbdaniels**

### CODE REVIEW

**Comment by kbjarkefur** [comment]
I made some edits to the security section.

Made it less specific to each product, and made android recommendations where we make an apple recommendation.

I know that was not what you meant, but it almost seemed as if 2FA was a part of pwd managers, so I split LastPass and Authy into two separate section to make it clear that they can be used without each other. 2FA is a much bigger commitment than pwd managers, so lets have ppl take one step at the time.

**Comment by kbjarkefur** [comment]
I added some promotion of WebEx. I found that most RAs still were using poor Skype connections.

**Comment by kbjarkefur** [comment]
This should be ready to merge now. @bbdaniels , do you want me to deploy? I will let you merge first, after you've looked at my last edits

**Comment by bbdaniels** [comment]
Added some final adjustments and merging. Go ahead and deploy if it's good to go!

**Pull request merged**
