### PR TITLE
elaborate citrix instructions

### PR DESCRIPTION
**Pull request by kbjarkefur**
Hey! Thanks @mrimal and @bbdaniels for helping me with this today. I added what I learned to this page.

Can you two look if there is anything you would add to this instructions? If there are no questions, then you @bbdaniels , can go ahead and merge to master when both of you are ok.

Then I can deploy the changes to the website.

Thanks!

### CODE REVIEW

**Comment by bbdaniels** [comment]
Made some revisions, good to go if you like them.

**Comment by kbjarkefur** [comment]
Thanks!

@mrimal , if you have a minute, please read this quickly and let me know if you are ok with the info, and then I will merge and deploy.

**Comment by mrimal** [comment]
It is possible to just add your Property number to access your local profile in it. It can be done through the Bookmarks tab in the myconnect.wbg.org profile. Should we add info to that as well?

**Comment by kbjarkefur** [comment]
that sounds super useful the one time you need something you saved in your documents folder. If you do not mind, please add instructions for how to do that!

**Comment by mrimal** [comment]
I added the instructions, please go through it and let me know and i can merge the pull request!

**Comment by bbdaniels** [comment]
Where in the URL exactly? That wasn't quite clear.

**Comment by kbjarkefur** [comment]
Looks good. I will merge!

Only me and Ben have write access to Master so that someone has the responsibility to have an overview of what goes up on the webpage.

**Comment by kbjarkefur** [comment]
This seems good to me, but I didn't follow it! Let's publish and if we get any feedback we will adjust, or next time I use citrix I will follow instructions! Thanks Mrijan!

**Comment by kbjarkefur** [comment]
deployed in a54c7077ecf74dabd5cb2a03cf26f3a3ac9dce72

**Pull request merged**
